### ISSUE TITLE
how to get this value

### ISSUE THREAD

**Issue by mrnuinfo** [4llonsy/sofar_solar#2]
how to get this value
SOFAR 3300TL-G3

![solarman](https://user-images.githubusercontent.com/37204769/136328255-35f4c851-9113-4174-b11f-310a32d3fc02.jpg)

**Comment by 4llonsy** [comment]
Since the grid power doesn't go through the inverter, its not possible to determine the grid power from the inverter. You can only find the grid voltage and frequency in inverter holding registers.
To get the grid power you should be able to get readings from power meter in your home. Hope this answers your question.

**Comment by mrnuinfo** [comment]
try this 0x0213

[SOFARSOLAR-ModBus-RTU-Communication-Protocol.pdf](https://github.com/4llonsy/sofar_solar/files/7299277/SOFARSOLAR-ModBus-RTU-Communication-Protocol.pdf)

![212927916_4007030349365249_5387298523453173958_n](https://user-images.githubusercontent.com/37204769/136330421-d644cf8f-37c3-4574-861b-0bdeb7695f4d.jpg)
